name: recops_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - python-dotenv
  - sentence-transformers
  - faiss-cpu
  - pygithub
  - langchain
  - langchain-community
  - huggingface_hub
  - qdrant-client
  - pip
  - pip:
    - torch
    - langchain-groq
