services:
  - type: web
    name: oss-analyzer-streamlit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_ui.py --server.port 10000 --server.enableCORS false"
    envVars:
      - key: PORT
        value: 10000
    plan: free
